# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'a003031d-a6f8-4202-9bcb-35aefbabc405'
  imageRepository: 'azure-vote'
  containerRegistry: 'devopsacrivank.azurecr.io'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        Dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: HelmDeploy@1
      inputs:
        azureSubscriptionForACR: 'Azure subscription 1 (f43b6291-a5e7-4469-ab79-653a0495f1fb)'
        azureResourceGroupForACR: 'devops-rg'
        azureContainerRegistry: 'devopsacrivank.azurecr.io'
        command: 'package'
        chartPath: 'helm/azure-vote'
        chartNameForACR: 'azure-vote'
        chartPathForACR: 'helm/azure-vote'
    - script: |
        pwd
        ls -al
        tree
    - task: HelmDeploy@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Azure subscription 1 (f43b6291-a5e7-4469-ab79-653a0495f1fb)'
        azureResourceGroup: 'devops-rg'
        kubernetesCluster: 'devops-aks-cluster'
        namespace: 'default'
        command: 'upgrade'
        chartType: 'Name'
        chartName: 'azure-vote'