# Redis settings
redis:
  image: redis:6.0

# Voting app settings
votingApp:
  repository: devopsacrivank.azurecr.io
  name: azure-vote
  image: "{{ .Values.votingApp.repository }}/{{ .Values.votingApp.name }}:{{.Values.votingApp.tag |  default .Chart.AppVersion}}"
  replicas: 1
  tag: 1
